### ISSUE TITLE
Tasks after seminar on 18th of October

### ISSUE THREAD

**Issue by trebi** [Qerts/pa165-java#1]
- [x] Everyone - create at least one EntityDao.
- [x] Everyone - create at least one test for EntityDao, which is not his own
---
- [x] @JozeFe - Design general Dao and create one Entity and Entity's Dao. Entity: **Employee**
- [x] @msmidik - Look on a way to design repository for some existing Entity, e.g. http://docs.spring.io/spring-data/data-commons/docs/1.6.1.RELEASE/reference/html/repositories.html Entity: **Vehicle** + **VehicleCategory**
- [x] @trebi - Set up test framework, create one Entity and Tests for it using in-memory database. Entity: **Journey**, DaoTest: **Employee**
- [x] @Qerts - Entity: **InspectionInterval** + **Inspection**

**Comment by trebi** [comment]
@Qerts: You haven't created a test for any Dao. There is still a test for `VehicleCategory` missing, please add it so you have something.

**Comment by JozeFe** [comment]
Everything is ok now, Im closing this issue.
