### ISSUE TITLE
Switch to GitHub flow from the Git flow

### ISSUE THREAD

**Issue by trebi** [Qerts/pa165-java#10]
On the last meeting, we have agreed to use some kind of Git flow instead of GitHub flow, i.e. use `dev` branch as the main branch and `master` branch for the stable releases. I have told you, that I don't care whether the branch on which are we working on is actually called `master` or `dev`, but I changed my mind.

1) GitHub interface is suited for GitHub flow rather than GitFlow. Perfect example is that if you open the project, you are by default on `master` branch rather than `dev` branch, which is for us as developers much more interesting. Another issue is that if we stick to the Git Flow, we will see `Compare & Pull Request` on the `dev` branch.
![githubflow](https://cloud.githubusercontent.com/assets/1706766/19781620/5ffde594-9c8a-11e6-8cc3-64e4e588860a.PNG)

2) I believe that Git flow is more for the bigger teams with separate roles, as Developers, QAs, testers and so on. 

**I suggest to switch to the proper GitHub flow**, i.e. use `master` as most up-to-date branch, pull requests for merging code into `master` and _tags_ for stable releases.

Read more about diffence between Gitflow and GitHub flow for instance here: https://lucamezzalira.com/2014/03/10/git-flow-vs-github-flow/

**Comment by JozeFe** [comment]
It's not big deal for me, if we will use dev or master branch. Last seminar we talk about this. If I'm right, we all decide for returning to GitHub flow. @Qerts if you agree with this solution please close this issue.
