### ISSUE TITLE
Make project multimodule

### ISSUE THREAD

**Issue by Qerts** [Qerts/pa165-java#23]
Change layout of your project to Multimodule Maven project (tutorial here http://maven.apache.org/guides/getting-started/index.html) Your project should have 3 separate modules:

- [x] DAO layer
- [x] Service Layer and Facade Layer implementation
- [x] API layer - just DTOs and facade interfaces!

**Comment by trebi** [comment]
Is everything done? Shall we close this?

**Comment by JozeFe** [comment]
I check it now, it's right done. I'm closing this issue
